#!/bin/sh

############################################################

# Script Name     :   Backlight
# Description     :   Prints the brightness level
# Args            :   none
# Author          :   Jellu Cat

############################################################

MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness)
BRIGHT=$(cat /sys/class/backlight/intel_backlight/brightness)

PERC=$(echo "scale=2; ($BRIGHT / $MAX) * 100" | bc -l)

############
# Printing #
############

printf "[BL] %.0f%%\n" $PERC
