#!/bin/sh

############################################################

# Script Name     :   Clock
# Description     :   Date and time
# Args            :   none
# Author          :   Jellu Cat

############################################################

CHARGE=$(cat /sys/class/power_supply/BAT0/charge_now)
MAX=$(cat /sys/class/power_supply/BAT0/charge_full)

PERC=$(echo "scale=2; ($CHARGE / $MAX) * 100" | bc -l)

############
# Printing #
############

printf "[CHG] %.0f%%\n" $PERC
